"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetFile = exports.AddFile = exports.Greeter = void 0;
var sendFiles_1 = require("./ftp/sendFiles");
var getFiles_1 = require("./ftp/getFiles");
var Greeter = function (name) { return "Hello ".concat(name); };
exports.Greeter = Greeter;
var AddFile = function (fileName) { return (0, sendFiles_1.sendFiles)(fileName); };
exports.AddFile = AddFile;
var GetFile = function (fileHash, fileName) { return (0, getFiles_1.getFiles)(fileHash, fileName); };
exports.GetFile = GetFile;
